
name: Coverity
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Coverity:

    runs-on: ubuntu-latest

    env:
      CSA: cov-analysis-linux64-2021.06
      COVERITY_PROJECT: github-io-sample
      BLDCMD: mvn -B package
      CHECKERS: --webapp-security

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Run tests
      run: mvn -B package 
